/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Forbidden model
 */
export interface Forbidden {
  /** Forbidden message */
  error: string;
  /** status code received from SSO */
  sso_status?: number;
}
