/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Gateway timeout model
 */
export interface GatewayTimeout {
  /** Gateway timeout message */
  error: string;
  /** number of seconds the request was given */
  timeout?: number;
}
