/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdMedals200Item = {
  /** created_at string */
  created_at: string;
  /** ID of the character who created this medal */
  creator_id: number;
  /** description string */
  description: string;
  /** medal_id integer */
  medal_id: number;
  /** title string */
  title: string;
};
