/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdMailMailId200RecipientsItemRecipientType } from './getCharactersCharacterIdMailMailId200RecipientsItemRecipientType';

/**
 * recipient object
 */
export type GetCharactersCharacterIdMailMailId200RecipientsItem = {
  /** recipient_id integer */
  recipient_id: number;
  /** recipient_type string */
  recipient_type: GetCharactersCharacterIdMailMailId200RecipientsItemRecipientType;
};
