/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdTitles200ItemGrantableRolesItem } from './getCorporationsCorporationIdTitles200ItemGrantableRolesItem';
import type { GetCorporationsCorporationIdTitles200ItemGrantableRolesAtBaseItem } from './getCorporationsCorporationIdTitles200ItemGrantableRolesAtBaseItem';
import type { GetCorporationsCorporationIdTitles200ItemGrantableRolesAtHqItem } from './getCorporationsCorporationIdTitles200ItemGrantableRolesAtHqItem';
import type { GetCorporationsCorporationIdTitles200ItemGrantableRolesAtOtherItem } from './getCorporationsCorporationIdTitles200ItemGrantableRolesAtOtherItem';
import type { GetCorporationsCorporationIdTitles200ItemRolesItem } from './getCorporationsCorporationIdTitles200ItemRolesItem';
import type { GetCorporationsCorporationIdTitles200ItemRolesAtBaseItem } from './getCorporationsCorporationIdTitles200ItemRolesAtBaseItem';
import type { GetCorporationsCorporationIdTitles200ItemRolesAtHqItem } from './getCorporationsCorporationIdTitles200ItemRolesAtHqItem';
import type { GetCorporationsCorporationIdTitles200ItemRolesAtOtherItem } from './getCorporationsCorporationIdTitles200ItemRolesAtOtherItem';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdTitles200Item = {
  /** grantable_roles array */
  grantable_roles?: GetCorporationsCorporationIdTitles200ItemGrantableRolesItem[];
  /** grantable_roles_at_base array */
  grantable_roles_at_base?: GetCorporationsCorporationIdTitles200ItemGrantableRolesAtBaseItem[];
  /** grantable_roles_at_hq array */
  grantable_roles_at_hq?: GetCorporationsCorporationIdTitles200ItemGrantableRolesAtHqItem[];
  /** grantable_roles_at_other array */
  grantable_roles_at_other?: GetCorporationsCorporationIdTitles200ItemGrantableRolesAtOtherItem[];
  /** name string */
  name?: string;
  /** roles array */
  roles?: GetCorporationsCorporationIdTitles200ItemRolesItem[];
  /** roles_at_base array */
  roles_at_base?: GetCorporationsCorporationIdTitles200ItemRolesAtBaseItem[];
  /** roles_at_hq array */
  roles_at_hq?: GetCorporationsCorporationIdTitles200ItemRolesAtHqItem[];
  /** roles_at_other array */
  roles_at_other?: GetCorporationsCorporationIdTitles200ItemRolesAtOtherItem[];
  /** title_id integer */
  title_id?: number;
};
