/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * shareholder_type string
 */
export type GetCorporationsCorporationIdShareholders200ItemShareholderType = typeof GetCorporationsCorporationIdShareholders200ItemShareholderType[keyof typeof GetCorporationsCorporationIdShareholders200ItemShareholderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdShareholders200ItemShareholderType = {
  character: 'character',
  corporation: 'corporation',
} as const;
