/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdStandings200ItemFromType } from './getCorporationsCorporationIdStandings200ItemFromType';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdStandings200Item = {
  /** from_id integer */
  from_id: number;
  /** from_type string */
  from_type: GetCorporationsCorporationIdStandings200ItemFromType;
  /** standing number */
  standing: number;
};
