/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdOrdersHistory200ItemRange } from './getCorporationsCorporationIdOrdersHistory200ItemRange';
import type { GetCorporationsCorporationIdOrdersHistory200ItemState } from './getCorporationsCorporationIdOrdersHistory200ItemState';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdOrdersHistory200Item = {
  /** Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration */
  duration: number;
  /** For buy orders, the amount of ISK in escrow */
  escrow?: number;
  /** True if the order is a bid (buy) order */
  is_buy_order?: boolean;
  /** Date and time when this order was issued */
  issued: string;
  /** The character who issued this order */
  issued_by?: number;
  /** ID of the location where order was placed */
  location_id: number;
  /** For buy orders, the minimum quantity that will be accepted in a matching sell order */
  min_volume?: number;
  /** Unique order ID */
  order_id: number;
  /** Cost per unit for this order */
  price: number;
  /** Valid order range, numbers are ranges in jumps */
  range: GetCorporationsCorporationIdOrdersHistory200ItemRange;
  /** ID of the region where order was placed */
  region_id: number;
  /** Current order state */
  state: GetCorporationsCorporationIdOrdersHistory200ItemState;
  /** The type ID of the item transacted in this order */
  type_id: number;
  /** Quantity of items still required or offered */
  volume_remain: number;
  /** Quantity of items required or offered at time order was placed */
  volume_total: number;
  /** The corporation wallet division used for this order */
  wallet_division: number;
};
