/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Summary of victory points gained by the given corporation for the enlisted faction
 */
export type GetCorporationsCorporationIdFwStats200VictoryPoints = {
  /** Last week's victory points gained by members of the given corporation */
  last_week: number;
  /** Total victory points gained since the given corporation enlisted */
  total: number;
  /** Yesterday's victory points gained by members of the given corporation */
  yesterday: number;
};
