/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * factory_details object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200PinsItemFactoryDetails = {
  /** schematic_id integer */
  schematic_id: number;
};
