/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdMembertracking200Item = {
  /** base_id integer */
  base_id?: number;
  /** character_id integer */
  character_id: number;
  /** location_id integer */
  location_id?: number;
  /** logoff_date string */
  logoff_date?: string;
  /** logon_date string */
  logon_date?: string;
  /** ship_type_id integer */
  ship_type_id?: number;
  /** start_date string */
  start_date?: string;
};
