/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * state string
 */
export type GetCorporationsCorporationIdStructures200ItemServicesItemState = typeof GetCorporationsCorporationIdStructures200ItemServicesItemState[keyof typeof GetCorporationsCorporationIdStructures200ItemServicesItemState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdStructures200ItemServicesItemState = {
  online: 'online',
  offline: 'offline',
  cleanup: 'cleanup',
} as const;
