/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdFleet200Role } from './getCharactersCharacterIdFleet200Role';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdFleet200 = {
  /** The character's current fleet ID */
  fleet_id: number;
  /** Member’s role in fleet */
  role: GetCharactersCharacterIdFleet200Role;
  /** ID of the squad the member is in. If not applicable, will be set to -1 */
  squad_id: number;
  /** ID of the wing the member is in. If not applicable, will be set to -1 */
  wing_id: number;
};
