/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * role_type string
 */
export type GetCorporationsCorporationIdRolesHistory200ItemRoleType = typeof GetCorporationsCorporationIdRolesHistory200ItemRoleType[keyof typeof GetCorporationsCorporationIdRolesHistory200ItemRoleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdRolesHistory200ItemRoleType = {
  grantable_roles: 'grantable_roles',
  grantable_roles_at_base: 'grantable_roles_at_base',
  grantable_roles_at_hq: 'grantable_roles_at_hq',
  grantable_roles_at_other: 'grantable_roles_at_other',
  roles: 'roles',
  roles_at_base: 'roles_at_base',
  roles_at_hq: 'roles_at_hq',
  roles_at_other: 'roles_at_other',
} as const;
