/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdStructures200ItemServicesItem } from './getCorporationsCorporationIdStructures200ItemServicesItem';
import type { GetCorporationsCorporationIdStructures200ItemState } from './getCorporationsCorporationIdStructures200ItemState';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdStructures200Item = {
  /** ID of the corporation that owns the structure */
  corporation_id: number;
  /** Date on which the structure will run out of fuel */
  fuel_expires?: string;
  /** The structure name */
  name?: string;
  /** The date and time when the structure's newly requested reinforcement times (e.g. next_reinforce_hour and next_reinforce_day) will take effect */
  next_reinforce_apply?: string;
  /** The requested change to reinforce_hour that will take effect at the time shown by next_reinforce_apply */
  next_reinforce_hour?: number;
  /** The id of the ACL profile for this citadel */
  profile_id: number;
  /** The hour of day that determines the four hour window when the structure will randomly exit its reinforcement periods and become vulnerable to attack against its armor and/or hull. The structure will become vulnerable at a random time that is +/- 2 hours centered on the value of this property */
  reinforce_hour?: number;
  /** Contains a list of service upgrades, and their state */
  services?: GetCorporationsCorporationIdStructures200ItemServicesItem[];
  /** state string */
  state: GetCorporationsCorporationIdStructures200ItemState;
  /** Date at which the structure will move to it's next state */
  state_timer_end?: string;
  /** Date at which the structure entered it's current state */
  state_timer_start?: string;
  /** The Item ID of the structure */
  structure_id: number;
  /** The solar system the structure is in */
  system_id: number;
  /** The type id of the structure */
  type_id: number;
  /** Date at which the structure will unanchor */
  unanchors_at?: string;
};
