/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * from_type string
 */
export type GetCharactersCharacterIdStandings200ItemFromType = typeof GetCharactersCharacterIdStandings200ItemFromType[keyof typeof GetCharactersCharacterIdStandings200ItemFromType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdStandings200ItemFromType = {
  agent: 'agent',
  npc_corp: 'npc_corp',
  faction: 'faction',
} as const;
