/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwLeaderboardsCharacters200KillsActiveTotalItem } from './getFwLeaderboardsCharacters200KillsActiveTotalItem';
import type { GetFwLeaderboardsCharacters200KillsLastWeekItem } from './getFwLeaderboardsCharacters200KillsLastWeekItem';
import type { GetFwLeaderboardsCharacters200KillsYesterdayItem } from './getFwLeaderboardsCharacters200KillsYesterdayItem';

/**
 * Top 100 rankings of pilots by number of kills from yesterday, last week and in total
 */
export type GetFwLeaderboardsCharacters200Kills = {
  /** Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered "active" if they have participated in faction warfare in the past 14 days */
  active_total: GetFwLeaderboardsCharacters200KillsActiveTotalItem[];
  /** Top 100 ranking of pilots by kills in the past week */
  last_week: GetFwLeaderboardsCharacters200KillsLastWeekItem[];
  /** Top 100 ranking of pilots by kills in the past day */
  yesterday: GetFwLeaderboardsCharacters200KillsYesterdayItem[];
};
