/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwStats200ItemKills } from './getFwStats200ItemKills';
import type { GetFwStats200ItemVictoryPoints } from './getFwStats200ItemVictoryPoints';

/**
 * 200 ok object
 */
export type GetFwStats200Item = {
  /** faction_id integer */
  faction_id: number;
  /** Summary of kills against an enemy faction for the given faction */
  kills: GetFwStats200ItemKills;
  /** How many pilots fight for the given faction */
  pilots: number;
  /** The number of solar systems controlled by the given faction */
  systems_controlled: number;
  /** Summary of victory points gained for the given faction */
  victory_points: GetFwStats200ItemVictoryPoints;
};
