/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Summary of kills against an enemy faction for the given faction
 */
export type GetFwStats200ItemKills = {
  /** Last week's total number of kills against enemy factions */
  last_week: number;
  /** Total number of kills against enemy factions since faction warfare began */
  total: number;
  /** Yesterday's total number of kills against enemy factions */
  yesterday: number;
};
