/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetKillmailsKillmailIdKillmailHash200AttackersItem } from './getKillmailsKillmailIdKillmailHash200AttackersItem';
import type { GetKillmailsKillmailIdKillmailHash200Victim } from './getKillmailsKillmailIdKillmailHash200Victim';

/**
 * 200 ok object
 */
export type GetKillmailsKillmailIdKillmailHash200 = {
  /** attackers array */
  attackers: GetKillmailsKillmailIdKillmailHash200AttackersItem[];
  /** ID of the killmail */
  killmail_id: number;
  /** Time that the victim was killed and the killmail generated
 */
  killmail_time: string;
  /** Moon if the kill took place at one */
  moon_id?: number;
  /** Solar system that the kill took place in
 */
  solar_system_id: number;
  /** victim object */
  victim: GetKillmailsKillmailIdKillmailHash200Victim;
  /** War if the killmail is generated in relation to an official war
 */
  war_id?: number;
};
