/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseStarsStarId200SpectralClass } from './getUniverseStarsStarId200SpectralClass';

/**
 * 200 ok object
 */
export type GetUniverseStarsStarId200 = {
  /** Age of star in years */
  age: number;
  /** luminosity number */
  luminosity: number;
  /** name string */
  name: string;
  /** radius integer */
  radius: number;
  /** solar_system_id integer */
  solar_system_id: number;
  /** spectral_class string */
  spectral_class: GetUniverseStarsStarId200SpectralClass;
  /** temperature integer */
  temperature: number;
  /** type_id integer */
  type_id: number;
};
