/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * destination object
 */
export type GetUniverseStargatesStargateId200Destination = {
  /** The stargate this stargate connects to */
  stargate_id: number;
  /** The solar system this stargate connects to */
  system_id: number;
};
