/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseBloodlines200Item = {
  /** bloodline_id integer */
  bloodline_id: number;
  /** charisma integer */
  charisma: number;
  /** corporation_id integer */
  corporation_id: number;
  /** description string */
  description: string;
  /** intelligence integer */
  intelligence: number;
  /** memory integer */
  memory: number;
  /** name string */
  name: string;
  /** perception integer */
  perception: number;
  /** race_id integer */
  race_id: number;
  /** ship_type_id integer */
  ship_type_id: number | null;
  /** willpower integer */
  willpower: number;
};
