/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * position object
 */
export type GetUniverseStationsStationId200Position = {
  /** x number */
  x: number;
  /** y number */
  y: number;
  /** z number */
  z: number;
};
