/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseAsteroidBeltsAsteroidBeltId200Position } from './getUniverseAsteroidBeltsAsteroidBeltId200Position';

/**
 * 200 ok object
 */
export type GetUniverseAsteroidBeltsAsteroidBeltId200 = {
  /** name string */
  name: string;
  /** position object */
  position: GetUniverseAsteroidBeltsAsteroidBeltId200Position;
  /** The solar system this asteroid belt is in */
  system_id: number;
};
