/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseMoonsMoonId200Position } from './getUniverseMoonsMoonId200Position';

/**
 * 200 ok object
 */
export type GetUniverseMoonsMoonId200 = {
  /** moon_id integer */
  moon_id: number;
  /** name string */
  name: string;
  /** position object */
  position: GetUniverseMoonsMoonId200Position;
  /** The solar system this moon is in */
  system_id: number;
};
