/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniversePlanetsPlanetId200Position } from './getUniversePlanetsPlanetId200Position';

/**
 * 200 ok object
 */
export type GetUniversePlanetsPlanetId200 = {
  /** name string */
  name: string;
  /** planet_id integer */
  planet_id: number;
  /** position object */
  position: GetUniversePlanetsPlanetId200Position;
  /** The solar system this planet is in */
  system_id: number;
  /** type_id integer */
  type_id: number;
};
