/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseConstellationsConstellationId200Position } from './getUniverseConstellationsConstellationId200Position';

/**
 * 200 ok object
 */
export type GetUniverseConstellationsConstellationId200 = {
  /** constellation_id integer */
  constellation_id: number;
  /** name string */
  name: string;
  /** position object */
  position: GetUniverseConstellationsConstellationId200Position;
  /** The region this constellation is in */
  region_id: number;
  /** systems array */
  systems: number[];
};
