/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id
 */
export type GetWarsWarId200Defender = {
  /** Alliance ID if and only if the defender is an alliance */
  alliance_id?: number;
  /** Corporation ID if and only if the defender is a corporation */
  corporation_id?: number;
  /** ISK value of ships the defender has killed */
  isk_destroyed: number;
  /** The number of ships the defender has killed */
  ships_killed: number;
};
