/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

export type LanguageParameter = typeof LanguageParameter[keyof typeof LanguageParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LanguageParameter = {
  en: 'en',
  'en-us': 'en-us',
  de: 'de',
  fr: 'fr',
  ja: 'ja',
  ru: 'ru',
  zh: 'zh',
  ko: 'ko',
  es: 'es',
} as const;
