/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PostUniverseNames200ItemCategory } from './postUniverseNames200ItemCategory';

/**
 * 200 ok object
 */
export type PostUniverseNames200Item = {
  /** category string */
  category: PostUniverseNames200ItemCategory;
  /** id integer */
  id: number;
  /** name string */
  name: string;
};
