/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { DatasourceParameter } from './datasourceParameter';
import type { TokenParameter } from './tokenParameter';

export type PostCharactersCharacterIdContactsParams = { datasource?: DatasourceParameter; label_ids?: number[]; standing: number; token?: TokenParameter; watched?: boolean };
