/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * response string
 */
export type PutCharactersCharacterIdCalendarEventIdBodyResponse = typeof PutCharactersCharacterIdCalendarEventIdBodyResponse[keyof typeof PutCharactersCharacterIdCalendarEventIdBodyResponse];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCharactersCharacterIdCalendarEventIdBodyResponse = {
  accepted: 'accepted',
  declined: 'declined',
  tentative: 'tentative',
} as const;
