/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PutCharactersCharacterIdCalendarEventIdBodyResponse } from './putCharactersCharacterIdCalendarEventIdBodyResponse';

/**
 * response object
 */
export type PutCharactersCharacterIdCalendarEventIdBody = {
  /** response string */
  response: PutCharactersCharacterIdCalendarEventIdBodyResponse;
};
