/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * contents object
 */
export type PutCharactersCharacterIdMailMailIdBody = {
  /** Labels to assign to the mail. Pre-existing labels are unassigned. */
  labels?: number[];
  /** Whether the mail is flagged as read */
  read?: boolean;
};
