/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * new_settings object
 */
export type PutFleetsFleetIdBody = {
  /** Should free-move be enabled in the fleet */
  is_free_move?: boolean;
  /** New fleet MOTD in CCP flavoured HTML */
  motd?: string;
};
