packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sveltejs/kit'
  - '@vercel/speed-insights'
  - aws-sdk
  - core-js-pure
  - es5-ext
  - esbuild
  - inngest-cli
  - prisma
  - protobufjs
  - sharp
