/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetAlliancesAllianceIdContacts200ItemContactType } from './getAlliancesAllianceIdContacts200ItemContactType';

/**
 * 200 ok object
 */
export type GetAlliancesAllianceIdContacts200Item = {
  /** contact_id integer */
  contact_id: number;
  /** contact_type string */
  contact_type: GetAlliancesAllianceIdContacts200ItemContactType;
  /** label_ids array */
  label_ids?: number[];
  /** Standing of the contact */
  standing: number;
};
