/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdNotifications200ItemSenderType } from './getCharactersCharacterIdNotifications200ItemSenderType';
import type { GetCharactersCharacterIdNotifications200ItemType } from './getCharactersCharacterIdNotifications200ItemType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdNotifications200Item = {
  /** is_read boolean */
  is_read?: boolean;
  /** notification_id integer */
  notification_id: number;
  /** sender_id integer */
  sender_id: number;
  /** sender_type string */
  sender_type: GetCharactersCharacterIdNotifications200ItemSenderType;
  /** text string */
  text?: string;
  /** timestamp string */
  timestamp: string;
  /** type string */
  type: GetCharactersCharacterIdNotifications200ItemType;
};
