/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdStarbases200ItemState } from './getCorporationsCorporationIdStarbases200ItemState';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdStarbases200Item = {
  /** The moon this starbase (POS) is anchored on, unanchored POSes do not have this information */
  moon_id?: number;
  /** When the POS onlined, for starbases (POSes) in online state */
  onlined_since?: string;
  /** When the POS will be out of reinforcement, for starbases (POSes) in reinforced state */
  reinforced_until?: string;
  /** Unique ID for this starbase (POS) */
  starbase_id: number;
  /** state string */
  state?: GetCorporationsCorporationIdStarbases200ItemState;
  /** The solar system this starbase (POS) is in, unanchored POSes have this information */
  system_id: number;
  /** Starbase (POS) type */
  type_id: number;
  /** When the POS started unanchoring, for starbases (POSes) in unanchoring state */
  unanchor_at?: string;
};
