/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCorporationCorporationIdMiningObserversObserverId200Item = {
  /** The character that did the mining
 */
  character_id: number;
  /** last_updated string */
  last_updated: string;
  /** quantity integer */
  quantity: number;
  /** The corporation id of the character at the time data was recorded.
 */
  recorded_corporation_id: number;
  /** type_id integer */
  type_id: number;
};
