/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdOpportunities200Item = {
  /** completed_at string */
  completed_at: string;
  /** task_id integer */
  task_id: number;
};
