/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdRoles200ItemGrantableRolesItem } from './getCorporationsCorporationIdRoles200ItemGrantableRolesItem';
import type { GetCorporationsCorporationIdRoles200ItemGrantableRolesAtBaseItem } from './getCorporationsCorporationIdRoles200ItemGrantableRolesAtBaseItem';
import type { GetCorporationsCorporationIdRoles200ItemGrantableRolesAtHqItem } from './getCorporationsCorporationIdRoles200ItemGrantableRolesAtHqItem';
import type { GetCorporationsCorporationIdRoles200ItemGrantableRolesAtOtherItem } from './getCorporationsCorporationIdRoles200ItemGrantableRolesAtOtherItem';
import type { GetCorporationsCorporationIdRoles200ItemRolesItem } from './getCorporationsCorporationIdRoles200ItemRolesItem';
import type { GetCorporationsCorporationIdRoles200ItemRolesAtBaseItem } from './getCorporationsCorporationIdRoles200ItemRolesAtBaseItem';
import type { GetCorporationsCorporationIdRoles200ItemRolesAtHqItem } from './getCorporationsCorporationIdRoles200ItemRolesAtHqItem';
import type { GetCorporationsCorporationIdRoles200ItemRolesAtOtherItem } from './getCorporationsCorporationIdRoles200ItemRolesAtOtherItem';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdRoles200Item = {
  /** character_id integer */
  character_id: number;
  /** grantable_roles array */
  grantable_roles?: GetCorporationsCorporationIdRoles200ItemGrantableRolesItem[];
  /** grantable_roles_at_base array */
  grantable_roles_at_base?: GetCorporationsCorporationIdRoles200ItemGrantableRolesAtBaseItem[];
  /** grantable_roles_at_hq array */
  grantable_roles_at_hq?: GetCorporationsCorporationIdRoles200ItemGrantableRolesAtHqItem[];
  /** grantable_roles_at_other array */
  grantable_roles_at_other?: GetCorporationsCorporationIdRoles200ItemGrantableRolesAtOtherItem[];
  /** roles array */
  roles?: GetCorporationsCorporationIdRoles200ItemRolesItem[];
  /** roles_at_base array */
  roles_at_base?: GetCorporationsCorporationIdRoles200ItemRolesAtBaseItem[];
  /** roles_at_hq array */
  roles_at_hq?: GetCorporationsCorporationIdRoles200ItemRolesAtHqItem[];
  /** roles_at_other array */
  roles_at_other?: GetCorporationsCorporationIdRoles200ItemRolesAtOtherItem[];
};
