/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdAlliancehistory200Item = {
  /** alliance_id integer */
  alliance_id?: number;
  /** True if the alliance has been closed */
  is_deleted?: boolean;
  /** An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous */
  record_id: number;
  /** start_date string */
  start_date: string;
};
