/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdMailLabels200LabelsItem } from './getCharactersCharacterIdMailLabels200LabelsItem';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdMailLabels200 = {
  /** labels array */
  labels?: GetCharactersCharacterIdMailLabels200LabelsItem[];
  /** total_unread_count integer */
  total_unread_count?: number;
};
