/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdContainersLogs200ItemAction } from './getCorporationsCorporationIdContainersLogs200ItemAction';
import type { GetCorporationsCorporationIdContainersLogs200ItemLocationFlag } from './getCorporationsCorporationIdContainersLogs200ItemLocationFlag';
import type { GetCorporationsCorporationIdContainersLogs200ItemPasswordType } from './getCorporationsCorporationIdContainersLogs200ItemPasswordType';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdContainersLogs200Item = {
  /** action string */
  action: GetCorporationsCorporationIdContainersLogs200ItemAction;
  /** ID of the character who performed the action. */
  character_id: number;
  /** ID of the container */
  container_id: number;
  /** Type ID of the container */
  container_type_id: number;
  /** location_flag string */
  location_flag: GetCorporationsCorporationIdContainersLogs200ItemLocationFlag;
  /** location_id integer */
  location_id: number;
  /** Timestamp when this log was created */
  logged_at: string;
  /** new_config_bitmask integer */
  new_config_bitmask?: number;
  /** old_config_bitmask integer */
  old_config_bitmask?: number;
  /** Type of password set if action is of type SetPassword or EnterPassword */
  password_type?: GetCorporationsCorporationIdContainersLogs200ItemPasswordType;
  /** Quantity of the item being acted upon */
  quantity?: number;
  /** Type ID of the item being acted upon */
  type_id?: number;
};
