/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdMedalsIssued200ItemStatus } from './getCorporationsCorporationIdMedalsIssued200ItemStatus';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdMedalsIssued200Item = {
  /** ID of the character who was rewarded this medal */
  character_id: number;
  /** issued_at string */
  issued_at: string;
  /** ID of the character who issued the medal */
  issuer_id: number;
  /** medal_id integer */
  medal_id: number;
  /** reason string */
  reason: string;
  /** status string */
  status: GetCorporationsCorporationIdMedalsIssued200ItemStatus;
};
