/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdAssets200ItemLocationFlag } from './getCharactersCharacterIdAssets200ItemLocationFlag';
import type { GetCharactersCharacterIdAssets200ItemLocationType } from './getCharactersCharacterIdAssets200ItemLocationType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdAssets200Item = {
  /** is_blueprint_copy boolean */
  is_blueprint_copy?: boolean;
  /** is_singleton boolean */
  is_singleton: boolean;
  /** item_id integer */
  item_id: number;
  /** location_flag string */
  location_flag: GetCharactersCharacterIdAssets200ItemLocationFlag;
  /** location_id integer */
  location_id: number;
  /** location_type string */
  location_type: GetCharactersCharacterIdAssets200ItemLocationType;
  /** quantity integer */
  quantity: number;
  /** type_id integer */
  type_id: number;
};
