/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdCalendarEventId200OwnerType } from './getCharactersCharacterIdCalendarEventId200OwnerType';

/**
 * Full details of a specific event
 */
export type GetCharactersCharacterIdCalendarEventId200 = {
  /** date string */
  date: string;
  /** Length in minutes */
  duration: number;
  /** event_id integer */
  event_id: number;
  /** importance integer */
  importance: number;
  /** owner_id integer */
  owner_id: number;
  /** owner_name string */
  owner_name: string;
  /** owner_type string */
  owner_type: GetCharactersCharacterIdCalendarEventId200OwnerType;
  /** response string */
  response: string;
  /** text string */
  text: string;
  /** title string */
  title: string;
};
