/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdBookmarks200ItemCoordinates } from './getCorporationsCorporationIdBookmarks200ItemCoordinates';
import type { GetCorporationsCorporationIdBookmarks200ItemItem } from './getCorporationsCorporationIdBookmarks200ItemItem';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdBookmarks200Item = {
  /** bookmark_id integer */
  bookmark_id: number;
  /** Optional object that is returned if a bookmark was made on a planet or a random location in space. */
  coordinates?: GetCorporationsCorporationIdBookmarks200ItemCoordinates;
  /** created string */
  created: string;
  /** creator_id integer */
  creator_id: number;
  /** folder_id integer */
  folder_id?: number;
  /** Optional object that is returned if a bookmark was made on a particular item. */
  item?: GetCorporationsCorporationIdBookmarks200ItemItem;
  /** label string */
  label: string;
  /** location_id integer */
  location_id: number;
  /** notes string */
  notes: string;
};
