/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * No image server for this datasource
 */
export type GetCharactersCharacterIdPortrait404 = {
  /** error message */
  error?: string;
};
