/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdPlanetsPlanetId200LinksItem } from './getCharactersCharacterIdPlanetsPlanetId200LinksItem';
import type { GetCharactersCharacterIdPlanetsPlanetId200PinsItem } from './getCharactersCharacterIdPlanetsPlanetId200PinsItem';
import type { GetCharactersCharacterIdPlanetsPlanetId200RoutesItem } from './getCharactersCharacterIdPlanetsPlanetId200RoutesItem';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200 = {
  /** links array */
  links: GetCharactersCharacterIdPlanetsPlanetId200LinksItem[];
  /** pins array */
  pins: GetCharactersCharacterIdPlanetsPlanetId200PinsItem[];
  /** routes array */
  routes: GetCharactersCharacterIdPlanetsPlanetId200RoutesItem[];
};
