/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * status string
 */
export type GetCorporationsCorporationIdMedalsIssued200ItemStatus = typeof GetCorporationsCorporationIdMedalsIssued200ItemStatus[keyof typeof GetCorporationsCorporationIdMedalsIssued200ItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdMedalsIssued200ItemStatus = {
  private: 'private',
  public: 'public',
} as const;
