/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Optional object that is returned if a bookmark was made on a planet or a random location in space.
 */
export type GetCharactersCharacterIdBookmarks200ItemCoordinates = {
  /** x number */
  x: number;
  /** y number */
  y: number;
  /** z number */
  z: number;
};
