/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Access is allowed only for entities with this level of standing or better
 */
export type GetCorporationsCorporationIdCustomsOffices200ItemStandingLevel = typeof GetCorporationsCorporationIdCustomsOffices200ItemStandingLevel[keyof typeof GetCorporationsCorporationIdCustomsOffices200ItemStandingLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdCustomsOffices200ItemStandingLevel = {
  bad: 'bad',
  excellent: 'excellent',
  good: 'good',
  neutral: 'neutral',
  terrible: 'terrible',
} as const;
