/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdStructures200ItemServicesItemState } from './getCorporationsCorporationIdStructures200ItemServicesItemState';

/**
 * service object
 */
export type GetCorporationsCorporationIdStructures200ItemServicesItem = {
  /** name string */
  name: string;
  /** state string */
  state: GetCorporationsCorporationIdStructures200ItemServicesItemState;
};
