/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Current order state
 */
export type GetCharactersCharacterIdOrdersHistory200ItemState = typeof GetCharactersCharacterIdOrdersHistory200ItemState[keyof typeof GetCharactersCharacterIdOrdersHistory200ItemState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdOrdersHistory200ItemState = {
  cancelled: 'cancelled',
  expired: 'expired',
} as const;
