/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Type of the contract
 */
export type GetCharactersCharacterIdContracts200ItemType = typeof GetCharactersCharacterIdContracts200ItemType[keyof typeof GetCharactersCharacterIdContracts200ItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdContracts200ItemType = {
  unknown: 'unknown',
  item_exchange: 'item_exchange',
  auction: 'auction',
  courier: 'courier',
  loan: 'loan',
} as const;
