/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

export type GetCharactersCharacterIdSearchCategoriesItem = typeof GetCharactersCharacterIdSearchCategoriesItem[keyof typeof GetCharactersCharacterIdSearchCategoriesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdSearchCategoriesItem = {
  agent: 'agent',
  alliance: 'alliance',
  character: 'character',
  constellation: 'constellation',
  corporation: 'corporation',
  faction: 'faction',
  inventory_type: 'inventory_type',
  region: 'region',
  solar_system: 'solar_system',
  station: 'station',
  structure: 'structure',
} as const;
