/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * gender string
 */
export type GetCharactersCharacterId200Gender = typeof GetCharactersCharacterId200Gender[keyof typeof GetCharactersCharacterId200Gender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterId200Gender = {
  female: 'female',
  male: 'male',
} as const;
