/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdWalletsDivisionJournal200ItemContextIdType } from './getCorporationsCorporationIdWalletsDivisionJournal200ItemContextIdType';
import type { GetCorporationsCorporationIdWalletsDivisionJournal200ItemRefType } from './getCorporationsCorporationIdWalletsDivisionJournal200ItemRefType';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdWalletsDivisionJournal200Item = {
  /** The amount of ISK given or taken from the wallet as a result of the given transaction. Positive when ISK is deposited into the wallet and negative when ISK is withdrawn */
  amount?: number;
  /** Wallet balance after transaction occurred */
  balance?: number;
  /** An ID that gives extra context to the particular transaction. Because of legacy reasons the context is completely different per ref_type and means different things. It is also possible to not have a context_id */
  context_id?: number;
  /** The type of the given context_id if present */
  context_id_type?: GetCorporationsCorporationIdWalletsDivisionJournal200ItemContextIdType;
  /** Date and time of transaction */
  date: string;
  /** The reason for the transaction, mirrors what is seen in the client */
  description: string;
  /** The id of the first party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name */
  first_party_id?: number;
  /** Unique journal reference ID */
  id: number;
  /** The user stated reason for the transaction. Only applies to some ref_types */
  reason?: string;
  /** "The transaction type for the given. transaction. Different transaction types will populate different attributes. Note: If you have an existing XML API application that is using ref_types, you will need to know which string ESI ref_type maps to which integer. You can look at the following file to see string->int mappings: https://github.com/ccpgames/eve-glue/blob/master/eve_glue/wallet_journal_ref.py" */
  ref_type: GetCorporationsCorporationIdWalletsDivisionJournal200ItemRefType;
  /** The id of the second party involved in the transaction. This attribute has no consistency and is different or non existant for particular ref_types. The description attribute will help make sense of what this attribute means. For more info about the given ID it can be dropped into the /universe/names/ ESI route to determine its type and name */
  second_party_id?: number;
  /** Tax amount received. Only applies to tax related transactions */
  tax?: number;
  /** The corporation ID receiving any tax paid. Only applies to tax related transactions */
  tax_receiver_id?: number;
};
