/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdStarbasesStarbaseId200Anchor } from './getCorporationsCorporationIdStarbasesStarbaseId200Anchor';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200FuelBayTake } from './getCorporationsCorporationIdStarbasesStarbaseId200FuelBayTake';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200FuelBayView } from './getCorporationsCorporationIdStarbasesStarbaseId200FuelBayView';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200FuelsItem } from './getCorporationsCorporationIdStarbasesStarbaseId200FuelsItem';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200Offline } from './getCorporationsCorporationIdStarbasesStarbaseId200Offline';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200Online } from './getCorporationsCorporationIdStarbasesStarbaseId200Online';
import type { GetCorporationsCorporationIdStarbasesStarbaseId200Unanchor } from './getCorporationsCorporationIdStarbasesStarbaseId200Unanchor';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdStarbasesStarbaseId200 = {
  /** allow_alliance_members boolean */
  allow_alliance_members: boolean;
  /** allow_corporation_members boolean */
  allow_corporation_members: boolean;
  /** Who can anchor starbase (POS) and its structures */
  anchor: GetCorporationsCorporationIdStarbasesStarbaseId200Anchor;
  /** attack_if_at_war boolean */
  attack_if_at_war: boolean;
  /** attack_if_other_security_status_dropping boolean */
  attack_if_other_security_status_dropping: boolean;
  /** Starbase (POS) will attack if target's security standing is lower than this value */
  attack_security_status_threshold?: number;
  /** Starbase (POS) will attack if target's standing is lower than this value */
  attack_standing_threshold?: number;
  /** Who can take fuel blocks out of the starbase (POS)'s fuel bay */
  fuel_bay_take: GetCorporationsCorporationIdStarbasesStarbaseId200FuelBayTake;
  /** Who can view the starbase (POS)'s fule bay. Characters either need to have required role or belong to the starbase (POS) owner's corporation or alliance, as described by the enum, all other access settings follows the same scheme */
  fuel_bay_view: GetCorporationsCorporationIdStarbasesStarbaseId200FuelBayView;
  /** Fuel blocks and other things that will be consumed when operating a starbase (POS) */
  fuels?: GetCorporationsCorporationIdStarbasesStarbaseId200FuelsItem[];
  /** Who can offline starbase (POS) and its structures */
  offline: GetCorporationsCorporationIdStarbasesStarbaseId200Offline;
  /** Who can online starbase (POS) and its structures */
  online: GetCorporationsCorporationIdStarbasesStarbaseId200Online;
  /** Who can unanchor starbase (POS) and its structures */
  unanchor: GetCorporationsCorporationIdStarbasesStarbaseId200Unanchor;
  /** True if the starbase (POS) is using alliance standings, otherwise using corporation's */
  use_alliance_standings: boolean;
};
