/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * location_type string
 */
export type GetCorporationsCorporationIdAssets200ItemLocationType = typeof GetCorporationsCorporationIdAssets200ItemLocationType[keyof typeof GetCorporationsCorporationIdAssets200ItemLocationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdAssets200ItemLocationType = {
  station: 'station',
  solar_system: 'solar_system',
  item: 'item',
  other: 'other',
} as const;
