/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * color string
 */
export type GetCharactersCharacterIdMailLabels200LabelsItemColor = typeof GetCharactersCharacterIdMailLabels200LabelsItemColor[keyof typeof GetCharactersCharacterIdMailLabels200LabelsItemColor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdMailLabels200LabelsItemColor = {
  '#0000fe': '#0000fe',
  '#006634': '#006634',
  '#0099ff': '#0099ff',
  '#00ff33': '#00ff33',
  '#01ffff': '#01ffff',
  '#349800': '#349800',
  '#660066': '#660066',
  '#666666': '#666666',
  '#999999': '#999999',
  '#99ffff': '#99ffff',
  '#9a0000': '#9a0000',
  '#ccff9a': '#ccff9a',
  '#e6e6e6': '#e6e6e6',
  '#fe0000': '#fe0000',
  '#ff6600': '#ff6600',
  '#ffff01': '#ffff01',
  '#ffffcd': '#ffffcd',
  '#ffffff': '#ffffff',
} as const;
