/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * skill object
 */
export type GetCharactersCharacterIdSkills200SkillsItem = {
  /** active_skill_level integer */
  active_skill_level: number;
  /** skill_id integer */
  skill_id: number;
  /** skillpoints_in_skill integer */
  skillpoints_in_skill: number;
  /** trained_skill_level integer */
  trained_skill_level: number;
};
