/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * To whom the contract is available
 */
export type GetCorporationsCorporationIdContracts200ItemAvailability = typeof GetCorporationsCorporationIdContracts200ItemAvailability[keyof typeof GetCorporationsCorporationIdContracts200ItemAvailability];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdContracts200ItemAvailability = {
  public: 'public',
  personal: 'personal',
  corporation: 'corporation',
  alliance: 'alliance',
} as const;
