/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * wallet object
 */
export type GetCorporationsCorporationIdDivisions200WalletItem = {
  /** division integer */
  division?: number;
  /** name string */
  name?: string;
};
