/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * The type of the given context_id if present
 */
export type GetCharactersCharacterIdWalletJournal200ItemContextIdType = typeof GetCharactersCharacterIdWalletJournal200ItemContextIdType[keyof typeof GetCharactersCharacterIdWalletJournal200ItemContextIdType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdWalletJournal200ItemContextIdType = {
  structure_id: 'structure_id',
  station_id: 'station_id',
  market_transaction_id: 'market_transaction_id',
  character_id: 'character_id',
  corporation_id: 'corporation_id',
  alliance_id: 'alliance_id',
  eve_system: 'eve_system',
  industry_job_id: 'industry_job_id',
  contract_id: 'contract_id',
  planet_id: 'planet_id',
  system_id: 'system_id',
  type_id: 'type_id',
} as const;
