/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * content object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200PinsItemContentsItem = {
  /** amount integer */
  amount: number;
  /** type_id integer */
  type_id: number;
};
