/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdStandings200ItemFromType } from './getCharactersCharacterIdStandings200ItemFromType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdStandings200Item = {
  /** from_id integer */
  from_id: number;
  /** from_type string */
  from_type: GetCharactersCharacterIdStandings200ItemFromType;
  /** standing number */
  standing: number;
};
