/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * contact_type string
 */
export type GetCorporationsCorporationIdContacts200ItemContactType = typeof GetCorporationsCorporationIdContacts200ItemContactType[keyof typeof GetCorporationsCorporationIdContacts200ItemContactType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdContacts200ItemContactType = {
  character: 'character',
  corporation: 'corporation',
  alliance: 'alliance',
  faction: 'faction',
} as const;
