/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetDogmaAttributesAttributeId200 = {
  /** attribute_id integer */
  attribute_id: number;
  /** default_value number */
  default_value?: number;
  /** description string */
  description?: string;
  /** display_name string */
  display_name?: string;
  /** high_is_good boolean */
  high_is_good?: boolean;
  /** icon_id integer */
  icon_id?: number;
  /** name string */
  name?: string;
  /** published boolean */
  published?: boolean;
  /** stackable boolean */
  stackable?: boolean;
  /** unit_id integer */
  unit_id?: number;
};
