/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwLeaderboardsCharacters200VictoryPointsActiveTotalItem } from './getFwLeaderboardsCharacters200VictoryPointsActiveTotalItem';
import type { GetFwLeaderboardsCharacters200VictoryPointsLastWeekItem } from './getFwLeaderboardsCharacters200VictoryPointsLastWeekItem';
import type { GetFwLeaderboardsCharacters200VictoryPointsYesterdayItem } from './getFwLeaderboardsCharacters200VictoryPointsYesterdayItem';

/**
 * Top 100 rankings of pilots by victory points from yesterday, last week and in total
 */
export type GetFwLeaderboardsCharacters200VictoryPoints = {
  /** Top 100 ranking of pilots active in faction warfare by total victory points. A pilot is considered "active" if they have participated in faction warfare in the past 14 days */
  active_total: GetFwLeaderboardsCharacters200VictoryPointsActiveTotalItem[];
  /** Top 100 ranking of pilots by victory points in the past week */
  last_week: GetFwLeaderboardsCharacters200VictoryPointsLastWeekItem[];
  /** Top 100 ranking of pilots by victory points in the past day */
  yesterday: GetFwLeaderboardsCharacters200VictoryPointsYesterdayItem[];
};
