/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwLeaderboardsCorporations200KillsActiveTotalItem } from './getFwLeaderboardsCorporations200KillsActiveTotalItem';
import type { GetFwLeaderboardsCorporations200KillsLastWeekItem } from './getFwLeaderboardsCorporations200KillsLastWeekItem';
import type { GetFwLeaderboardsCorporations200KillsYesterdayItem } from './getFwLeaderboardsCorporations200KillsYesterdayItem';

/**
 * Top 10 rankings of corporations by number of kills from yesterday, last week and in total
 */
export type GetFwLeaderboardsCorporations200Kills = {
  /** Top 10 ranking of corporations active in faction warfare by total kills. A corporation is considered "active" if they have participated in faction warfare in the past 14 days */
  active_total: GetFwLeaderboardsCorporations200KillsActiveTotalItem[];
  /** Top 10 ranking of corporations by kills in the past week */
  last_week: GetFwLeaderboardsCorporations200KillsLastWeekItem[];
  /** Top 10 ranking of corporations by kills in the past day */
  yesterday: GetFwLeaderboardsCorporations200KillsYesterdayItem[];
};
