/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * contested string
 */
export type GetFwSystems200ItemContested = typeof GetFwSystems200ItemContested[keyof typeof GetFwSystems200ItemContested];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFwSystems200ItemContested = {
  captured: 'captured',
  contested: 'contested',
  uncontested: 'uncontested',
  vulnerable: 'vulnerable',
} as const;
