/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFleetsFleetIdMembers200ItemRole } from './getFleetsFleetIdMembers200ItemRole';

/**
 * 200 ok object
 */
export type GetFleetsFleetIdMembers200Item = {
  /** character_id integer */
  character_id: number;
  /** join_time string */
  join_time: string;
  /** Member’s role in fleet */
  role: GetFleetsFleetIdMembers200ItemRole;
  /** Localized role names */
  role_name: string;
  /** ship_type_id integer */
  ship_type_id: number;
  /** Solar system the member is located in */
  solar_system_id: number;
  /** ID of the squad the member is in. If not applicable, will be set to -1 */
  squad_id: number;
  /** Station in which the member is docked in, if applicable */
  station_id?: number;
  /** Whether the member take fleet warps */
  takes_fleet_warp: boolean;
  /** ID of the wing the member is in. If not applicable, will be set to -1 */
  wing_id: number;
};
