/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwSystems200ItemContested } from './getFwSystems200ItemContested';

/**
 * 200 ok object
 */
export type GetFwSystems200Item = {
  /** contested string */
  contested: GetFwSystems200ItemContested;
  /** occupier_faction_id integer */
  occupier_faction_id: number;
  /** owner_faction_id integer */
  owner_faction_id: number;
  /** solar_system_id integer */
  solar_system_id: number;
  /** victory_points integer */
  victory_points: number;
  /** victory_points_threshold integer */
  victory_points_threshold: number;
};
