/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetFleetsFleetId200 = {
  /** Is free-move enabled */
  is_free_move: boolean;
  /** Does the fleet have an active fleet advertisement */
  is_registered: boolean;
  /** Is EVE Voice enabled */
  is_voice_enabled: boolean;
  /** Fleet MOTD in CCP flavoured HTML */
  motd: string;
};
