/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Member’s role in fleet
 */
export type GetFleetsFleetIdMembers200ItemRole = typeof GetFleetsFleetIdMembers200ItemRole[keyof typeof GetFleetsFleetIdMembers200ItemRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFleetsFleetIdMembers200ItemRole = {
  fleet_commander: 'fleet_commander',
  wing_commander: 'wing_commander',
  squad_commander: 'squad_commander',
  squad_member: 'squad_member',
} as const;
