/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetInsurancePrices200ItemLevelsItem } from './getInsurancePrices200ItemLevelsItem';

/**
 * 200 ok object
 */
export type GetInsurancePrices200Item = {
  /** A list of a available insurance levels for this ship type */
  levels: GetInsurancePrices200ItemLevelsItem[];
  /** type_id integer */
  type_id: number;
};
