/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * item object
 */
export type GetKillmailsKillmailIdKillmailHash200VictimItemsItemItemsItem = {
  /** flag integer */
  flag: number;
  /** item_type_id integer */
  item_type_id: number;
  /** quantity_destroyed integer */
  quantity_destroyed?: number;
  /** quantity_dropped integer */
  quantity_dropped?: number;
  /** singleton integer */
  singleton: number;
};
