/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetMarketsRegionIdOrders200ItemRange } from './getMarketsRegionIdOrders200ItemRange';

/**
 * 200 ok object
 */
export type GetMarketsRegionIdOrders200Item = {
  /** duration integer */
  duration: number;
  /** is_buy_order boolean */
  is_buy_order: boolean;
  /** issued string */
  issued: string;
  /** location_id integer */
  location_id: number;
  /** min_volume integer */
  min_volume: number;
  /** order_id integer */
  order_id: number;
  /** price number */
  price: number;
  /** range string */
  range: GetMarketsRegionIdOrders200ItemRange;
  /** The solar system this order was placed */
  system_id: number;
  /** type_id integer */
  type_id: number;
  /** volume_remain integer */
  volume_remain: number;
  /** volume_total integer */
  volume_total: number;
};
