/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

export type GetMarketsRegionIdOrdersOrderType = typeof GetMarketsRegionIdOrdersOrderType[keyof typeof GetMarketsRegionIdOrdersOrderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMarketsRegionIdOrdersOrderType = {
  buy: 'buy',
  sell: 'sell',
  all: 'all',
} as const;
