/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetMarketsGroupsMarketGroupId200 = {
  /** description string */
  description: string;
  /** market_group_id integer */
  market_group_id: number;
  /** name string */
  name: string;
  /** parent_group_id integer */
  parent_group_id?: number;
  /** types array */
  types: number[];
};
