/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * range string
 */
export type GetMarketsStructuresStructureId200ItemRange = typeof GetMarketsStructuresStructureId200ItemRange[keyof typeof GetMarketsStructuresStructureId200ItemRange];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMarketsStructuresStructureId200ItemRange = {
  station: 'station',
  region: 'region',
  solarsystem: 'solarsystem',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  NUMBER_10: '10',
  NUMBER_20: '20',
  NUMBER_30: '30',
  NUMBER_40: '40',
} as const;
