/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * participant object
 */
export type GetSovereigntyCampaigns200ItemParticipantsItem = {
  /** alliance_id integer */
  alliance_id: number;
  /** score number */
  score: number;
};
