/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

export type GetUniverseStructuresFilter = typeof GetUniverseStructuresFilter[keyof typeof GetUniverseStructuresFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUniverseStructuresFilter = {
  market: 'market',
  manufacturing_basic: 'manufacturing_basic',
} as const;
