/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseCategoriesCategoryId200 = {
  /** category_id integer */
  category_id: number;
  /** groups array */
  groups: number[];
  /** name string */
  name: string;
  /** published boolean */
  published: boolean;
};
