/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseSystemJumps200Item = {
  /** ship_jumps integer */
  ship_jumps: number;
  /** system_id integer */
  system_id: number;
};
