/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseGraphicsGraphicId200 = {
  /** collision_file string */
  collision_file?: string;
  /** graphic_file string */
  graphic_file?: string;
  /** graphic_id integer */
  graphic_id: number;
  /** icon_folder string */
  icon_folder?: string;
  /** sof_dna string */
  sof_dna?: string;
  /** sof_fation_name string */
  sof_fation_name?: string;
  /** sof_hull_name string */
  sof_hull_name?: string;
  /** sof_race_name string */
  sof_race_name?: string;
};
