/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseSchematicsSchematicId200 = {
  /** Time in seconds to process a run */
  cycle_time: number;
  /** schematic_name string */
  schematic_name: string;
};
