/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseStructuresStructureId200Position } from './getUniverseStructuresStructureId200Position';

/**
 * 200 ok object
 */
export type GetUniverseStructuresStructureId200 = {
  /** The full name of the structure */
  name: string;
  /** The ID of the corporation who owns this particular structure */
  owner_id: number;
  /** Coordinates of the structure in Cartesian space relative to the Sun, in metres.
 */
  position?: GetUniverseStructuresStructureId200Position;
  /** solar_system_id integer */
  solar_system_id: number;
  /** type_id integer */
  type_id?: number;
};
