/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseStargatesStargateId200Destination } from './getUniverseStargatesStargateId200Destination';
import type { GetUniverseStargatesStargateId200Position } from './getUniverseStargatesStargateId200Position';

/**
 * 200 ok object
 */
export type GetUniverseStargatesStargateId200 = {
  /** destination object */
  destination: GetUniverseStargatesStargateId200Destination;
  /** name string */
  name: string;
  /** position object */
  position: GetUniverseStargatesStargateId200Position;
  /** stargate_id integer */
  stargate_id: number;
  /** The solar system this stargate is in */
  system_id: number;
  /** type_id integer */
  type_id: number;
};
