/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * ally object
 */
export type GetWarsWarId200AlliesItem = {
  /** Alliance ID if and only if this ally is an alliance */
  alliance_id?: number;
  /** Corporation ID if and only if this ally is a corporation */
  corporation_id?: number;
};
