/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type PostCharactersCharacterIdAssetsNames200Item = {
  /** item_id integer */
  item_id: number;
  /** name string */
  name: string;
};
