/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 201 created object
 */
export type PostFleetsFleetIdWingsWingIdSquads201 = {
  /** The squad_id of the newly created squad */
  squad_id: number;
};
