/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * category string
 */
export type PostUniverseNames200ItemCategory = typeof PostUniverseNames200ItemCategory[keyof typeof PostUniverseNames200ItemCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUniverseNames200ItemCategory = {
  alliance: 'alliance',
  character: 'character',
  constellation: 'constellation',
  corporation: 'corporation',
  inventory_type: 'inventory_type',
  region: 'region',
  solar_system: 'solar_system',
  station: 'station',
  faction: 'faction',
} as const;
