/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PostCharactersCharacterIdFittingsBodyItemsItemFlag } from './postCharactersCharacterIdFittingsBodyItemsItemFlag';

/**
 * item object
 */
export type PostCharactersCharacterIdFittingsBodyItemsItem = {
  /** Fitting location for the item. Entries placed in 'Invalid' will be discarded. If this leaves the fitting with nothing, it will cause an error. */
  flag: PostCharactersCharacterIdFittingsBodyItemsItemFlag;
  /** quantity integer */
  quantity: number;
  /** type_id integer */
  type_id: number;
};
