/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 422 unprocessable entity object
 */
export type PostFleetsFleetIdMembers422 = {
  /** error message */
  error?: string;
};
