/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PostCharactersCharacterIdFittingsBodyItemsItem } from './postCharactersCharacterIdFittingsBodyItemsItem';

/**
 * fitting object
 */
export type PostCharactersCharacterIdFittingsBody = {
  /** description string */
  description: string;
  /** items array */
  items: PostCharactersCharacterIdFittingsBodyItemsItem[];
  /** name string */
  name: string;
  /** ship_type_id integer */
  ship_type_id: number;
};
