/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * If a character is invited with the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is invited with the `wing_commander` role, only `wing_id` should be specified. If a character is invited with the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is invited with the `squad_member` role, `wing_id` and `squad_id` should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.
 */
export type PostFleetsFleetIdMembersBodyRole = typeof PostFleetsFleetIdMembersBodyRole[keyof typeof PostFleetsFleetIdMembersBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostFleetsFleetIdMembersBodyRole = {
  fleet_commander: 'fleet_commander',
  wing_commander: 'wing_commander',
  squad_commander: 'squad_commander',
  squad_member: 'squad_member',
} as const;
