import { bootstrapDatabase } from "./bootstrap";
import {
  backfillEveKillAllianceIds,
  backfillEveKillCharacterIds,
  backfillEveKillCorporationIds,
  backfillEveRefKillmails,
  backfillEveRefWars,
  processRedisAllianceIds,
  processRedisCharacterIds,
  processRedisCorporationIds,
  processRedisWars,
  scrapeEsiAlliances,
  scrapeEsiAncestries,
  scrapeEsiBloodlines,
  scrapeEsiCategories,
  scrapeEsiConstellations,
  scrapeEsiCorporations,
  scrapeEsiDogmaAttributes,
  scrapeEsiDogmaEffects,
  scrapeEsiFactions,
  scrapeEsiGraphics,
  scrapeEsiGroups,
  scrapeEsiLoyaltyStoreOffers,
  scrapeEsiMarketGroups,
  scrapeEsiMoons,
  scrapeEsiNpcCorporations,
  scrapeEsiPlanets,
  scrapeEsiRaces,
  scrapeEsiRegions,
  scrapeEsiSolarSystems,
  scrapeEsiStargates,
  scrapeEsiStations,
  scrapeEsiTypes,
  scrapeEsiWars,
  scrapeHoboleaksAgentTypes,
  scrapeHoboleaksDogmaEffectCategories,
  scrapeHoboleaksDogmaUnits,
  scrapeSdeAgents,
  scrapeSdeDogmaAttributeCategories,
  scrapeSdeDogmaEffectModifiers,
  scrapeSdeIcons,
  scrapeSdeNpcCorporationDivisions,
  scrapeSdeRaces,
  scrapeSdeStationServices,
  scrapeZkillboardRecentKills,
  updateWars,
} from "./scrape";
import { testPing } from "./test";

export const functions = [
  backfillEveKillAllianceIds,
  backfillEveKillCharacterIds,
  backfillEveKillCorporationIds,
  backfillEveRefKillmails,
  backfillEveRefWars,
  bootstrapDatabase,
  processRedisAllianceIds,
  processRedisCharacterIds,
  processRedisCorporationIds,
  processRedisWars,
  scrapeEsiAlliances,
  scrapeEsiAncestries,
  scrapeEsiBloodlines,
  scrapeEsiCategories,
  scrapeEsiConstellations,
  scrapeEsiCorporations,
  scrapeEsiDogmaAttributes,
  scrapeEsiDogmaEffects,
  scrapeEsiFactions,
  scrapeEsiGraphics,
  scrapeEsiGroups,
  scrapeEsiLoyaltyStoreOffers,
  scrapeEsiMarketGroups,
  scrapeEsiMoons,
  scrapeEsiNpcCorporations,
  scrapeEsiPlanets,
  scrapeEsiRaces,
  scrapeEsiRegions,
  scrapeEsiSolarSystems,
  scrapeEsiStargates,
  scrapeEsiStations,
  scrapeEsiTypes,
  scrapeEsiWars,
  scrapeHoboleaksAgentTypes,
  scrapeHoboleaksDogmaEffectCategories,
  scrapeHoboleaksDogmaUnits,
  scrapeSdeAgents,
  scrapeSdeDogmaAttributeCategories,
  scrapeSdeDogmaEffectModifiers,
  scrapeSdeIcons,
  scrapeSdeNpcCorporationDivisions,
  scrapeSdeRaces,
  scrapeSdeStationServices,
  scrapeZkillboardRecentKills,
  testPing,
  updateWars,
];

export * from "./scrape";
export * from "./test";
export * from "./bootstrap";
