import {
  scrapeEsiAlliances,
  scrapeEsiAncestries,
  scrapeEsiBloodlines,
  scrapeEsiCategories,
  scrapeEsiConstellations,
  scrapeEsiCorporations,
  scrapeEsiDogmaAttributes,
  scrapeEsiDogmaEffects,
  scrapeEsiFactions,
  scrapeEsiGraphics,
  scrapeEsiGroups,
  scrapeEsiLoyaltyStoreOffers,
  scrapeEsiMarketGroups,
  scrapeEsiMoons,
  scrapeEsiNpcCorporations,
  scrapeEsiPlanets,
  scrapeEsiRaces,
  scrapeEsiRegions,
  scrapeEsiSolarSystems,
  scrapeEsiTypes,
} from "./scrape";
import { testPing } from "./test";

export const functions = [
  testPing,
  scrapeEsiAlliances,
  scrapeEsiAncestries,
  scrapeEsiBloodlines,
  scrapeEsiCategories,
  scrapeEsiCorporations,
  scrapeEsiConstellations,
  scrapeEsiDogmaAttributes,
  scrapeEsiDogmaEffects,
  scrapeEsiFactions,
  scrapeEsiGraphics,
  scrapeEsiGroups,
  scrapeEsiLoyaltyStoreOffers,
  scrapeEsiMarketGroups,
  scrapeEsiMoons,
  scrapeEsiNpcCorporations,
  scrapeEsiPlanets,
  scrapeEsiRaces,
  scrapeEsiRegions,
  scrapeEsiSolarSystems,
  scrapeEsiTypes,
];

export * from "./scrape";
export * from "./test";
