/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

export type DatasourceParameter = typeof DatasourceParameter[keyof typeof DatasourceParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasourceParameter = {
  tranquility: 'tranquility',
} as const;
