/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdPlanetsPlanetId200PinsItemContentsItem } from './getCharactersCharacterIdPlanetsPlanetId200PinsItemContentsItem';
import type { GetCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetails } from './getCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetails';
import type { GetCharactersCharacterIdPlanetsPlanetId200PinsItemFactoryDetails } from './getCharactersCharacterIdPlanetsPlanetId200PinsItemFactoryDetails';

/**
 * pin object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200PinsItem = {
  /** contents array */
  contents?: GetCharactersCharacterIdPlanetsPlanetId200PinsItemContentsItem[];
  /** expiry_time string */
  expiry_time?: string;
  /** extractor_details object */
  extractor_details?: GetCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetails;
  /** factory_details object */
  factory_details?: GetCharactersCharacterIdPlanetsPlanetId200PinsItemFactoryDetails;
  /** install_time string */
  install_time?: string;
  /** last_cycle_start string */
  last_cycle_start?: string;
  /** latitude number */
  latitude: number;
  /** longitude number */
  longitude: number;
  /** pin_id integer */
  pin_id: number;
  /** schematic_id integer */
  schematic_id?: number;
  /** type_id integer */
  type_id: number;
};
