/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Valid order range, numbers are ranges in jumps
 */
export type GetCharactersCharacterIdOrders200ItemRange = typeof GetCharactersCharacterIdOrders200ItemRange[keyof typeof GetCharactersCharacterIdOrders200ItemRange];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdOrders200ItemRange = {
  NUMBER_1: '1',
  NUMBER_10: '10',
  NUMBER_2: '2',
  NUMBER_20: '20',
  NUMBER_3: '3',
  NUMBER_30: '30',
  NUMBER_4: '4',
  NUMBER_40: '40',
  NUMBER_5: '5',
  region: 'region',
  solarsystem: 'solarsystem',
  station: 'station',
} as const;
