/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { DatasourceParameter } from './datasourceParameter';
import type { PageParameter } from './pageParameter';
import type { TokenParameter } from './tokenParameter';

export type GetCorporationCorporationIdMiningObserversParams = { datasource?: DatasourceParameter; page?: PageParameter; token?: TokenParameter };
