/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdFwStats200Kills } from './getCorporationsCorporationIdFwStats200Kills';
import type { GetCorporationsCorporationIdFwStats200VictoryPoints } from './getCorporationsCorporationIdFwStats200VictoryPoints';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdFwStats200 = {
  /** The enlistment date of the given corporation into faction warfare. Will not be included if corporation is not enlisted in faction warfare */
  enlisted_on?: string;
  /** The faction the given corporation is enlisted to fight for. Will not be included if corporation is not enlisted in faction warfare */
  faction_id?: number;
  /** Summary of kills done by the given corporation against enemy factions */
  kills: GetCorporationsCorporationIdFwStats200Kills;
  /** How many pilots the enlisted corporation has. Will not be included if corporation is not enlisted in faction warfare */
  pilots?: number;
  /** Summary of victory points gained by the given corporation for the enlisted faction */
  victory_points: GetCorporationsCorporationIdFwStats200VictoryPoints;
};
