/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdLoyaltyPoints200Item = {
  /** corporation_id integer */
  corporation_id: number;
  /** loyalty_points integer */
  loyalty_points: number;
};
