/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * The category of the observing entity
 */
export type GetCorporationCorporationIdMiningObservers200ItemObserverType = typeof GetCorporationCorporationIdMiningObservers200ItemObserverType[keyof typeof GetCorporationCorporationIdMiningObservers200ItemObserverType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationCorporationIdMiningObservers200ItemObserverType = {
  structure: 'structure',
} as const;
