/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdMedals200ItemGraphicsItem } from './getCharactersCharacterIdMedals200ItemGraphicsItem';
import type { GetCharactersCharacterIdMedals200ItemStatus } from './getCharactersCharacterIdMedals200ItemStatus';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdMedals200Item = {
  /** corporation_id integer */
  corporation_id: number;
  /** date string */
  date: string;
  /** description string */
  description: string;
  /** graphics array */
  graphics: GetCharactersCharacterIdMedals200ItemGraphicsItem[];
  /** issuer_id integer */
  issuer_id: number;
  /** medal_id integer */
  medal_id: number;
  /** reason string */
  reason: string;
  /** status string */
  status: GetCharactersCharacterIdMedals200ItemStatus;
  /** title string */
  title: string;
};
