/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * planet_type string
 */
export type GetCharactersCharacterIdPlanets200ItemPlanetType = typeof GetCharactersCharacterIdPlanets200ItemPlanetType[keyof typeof GetCharactersCharacterIdPlanets200ItemPlanetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdPlanets200ItemPlanetType = {
  temperate: 'temperate',
  barren: 'barren',
  oceanic: 'oceanic',
  ice: 'ice',
  gas: 'gas',
  lava: 'lava',
  storm: 'storm',
  plasma: 'plasma',
} as const;
