/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * recipient_type string
 */
export type GetCharactersCharacterIdMail200ItemRecipientsItemRecipientType = typeof GetCharactersCharacterIdMail200ItemRecipientsItemRecipientType[keyof typeof GetCharactersCharacterIdMail200ItemRecipientsItemRecipientType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdMail200ItemRecipientsItemRecipientType = {
  alliance: 'alliance',
  character: 'character',
  corporation: 'corporation',
  mailing_list: 'mailing_list',
} as const;
