/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * link object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200LinksItem = {
  /** destination_pin_id integer */
  destination_pin_id: number;
  /** link_level integer */
  link_level: number;
  /** source_pin_id integer */
  source_pin_id: number;
};
