/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdAssets200ItemLocationFlag } from './getCorporationsCorporationIdAssets200ItemLocationFlag';
import type { GetCorporationsCorporationIdAssets200ItemLocationType } from './getCorporationsCorporationIdAssets200ItemLocationType';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdAssets200Item = {
  /** is_blueprint_copy boolean */
  is_blueprint_copy?: boolean;
  /** is_singleton boolean */
  is_singleton: boolean;
  /** item_id integer */
  item_id: number;
  /** location_flag string */
  location_flag: GetCorporationsCorporationIdAssets200ItemLocationFlag;
  /** location_id integer */
  location_id: number;
  /** location_type string */
  location_type: GetCorporationsCorporationIdAssets200ItemLocationType;
  /** quantity integer */
  quantity: number;
  /** type_id integer */
  type_id: number;
};
