/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * event_response string
 */
export type GetCharactersCharacterIdCalendarEventIdAttendees200ItemEventResponse = typeof GetCharactersCharacterIdCalendarEventIdAttendees200ItemEventResponse[keyof typeof GetCharactersCharacterIdCalendarEventIdAttendees200ItemEventResponse];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdCalendarEventIdAttendees200ItemEventResponse = {
  declined: 'declined',
  not_responded: 'not_responded',
  accepted: 'accepted',
  tentative: 'tentative',
} as const;
