/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Who can anchor starbase (POS) and its structures
 */
export type GetCorporationsCorporationIdStarbasesStarbaseId200Anchor = typeof GetCorporationsCorporationIdStarbasesStarbaseId200Anchor[keyof typeof GetCorporationsCorporationIdStarbasesStarbaseId200Anchor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdStarbasesStarbaseId200Anchor = {
  alliance_member: 'alliance_member',
  config_starbase_equipment_role: 'config_starbase_equipment_role',
  corporation_member: 'corporation_member',
  starbase_fuel_technician_role: 'starbase_fuel_technician_role',
} as const;
