/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdRoles200RolesItem } from './getCharactersCharacterIdRoles200RolesItem';
import type { GetCharactersCharacterIdRoles200RolesAtBaseItem } from './getCharactersCharacterIdRoles200RolesAtBaseItem';
import type { GetCharactersCharacterIdRoles200RolesAtHqItem } from './getCharactersCharacterIdRoles200RolesAtHqItem';
import type { GetCharactersCharacterIdRoles200RolesAtOtherItem } from './getCharactersCharacterIdRoles200RolesAtOtherItem';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdRoles200 = {
  /** roles array */
  roles?: GetCharactersCharacterIdRoles200RolesItem[];
  /** roles_at_base array */
  roles_at_base?: GetCharactersCharacterIdRoles200RolesAtBaseItem[];
  /** roles_at_hq array */
  roles_at_hq?: GetCharactersCharacterIdRoles200RolesAtHqItem[];
  /** roles_at_other array */
  roles_at_other?: GetCharactersCharacterIdRoles200RolesAtOtherItem[];
};
