/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdContactsLabels200Item = {
  /** label_id integer */
  label_id: number;
  /** label_name string */
  label_name: string;
};
