/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFleetsFleetIdWings200ItemSquadsItem } from './getFleetsFleetIdWings200ItemSquadsItem';

/**
 * 200 ok object
 */
export type GetFleetsFleetIdWings200Item = {
  /** id integer */
  id: number;
  /** name string */
  name: string;
  /** squads array */
  squads: GetFleetsFleetIdWings200ItemSquadsItem[];
};
