/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * active_total object
 */
export type GetFwLeaderboards200KillsActiveTotalItem = {
  /** Amount of kills */
  amount?: number;
  /** faction_id integer */
  faction_id?: number;
};
