/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * yesterday object
 */
export type GetFwLeaderboardsCharacters200VictoryPointsYesterdayItem = {
  /** Amount of victory points */
  amount?: number;
  /** character_id integer */
  character_id?: number;
};
