/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetIncursions200ItemState } from './getIncursions200ItemState';

/**
 * 200 ok object
 */
export type GetIncursions200Item = {
  /** The constellation id in which this incursion takes place */
  constellation_id: number;
  /** The attacking faction's id */
  faction_id: number;
  /** Whether the final encounter has boss or not */
  has_boss: boolean;
  /** A list of infested solar system ids that are a part of this incursion */
  infested_solar_systems: number[];
  /** Influence of this incursion as a float from 0 to 1 */
  influence: number;
  /** Staging solar system for this incursion */
  staging_solar_system_id: number;
  /** The state of this incursion */
  state: GetIncursions200ItemState;
  /** The type of this incursion */
  type: string;
};
