/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * level object
 */
export type GetInsurancePrices200ItemLevelsItem = {
  /** cost number */
  cost: number;
  /** Localized insurance level */
  name: string;
  /** payout number */
  payout: number;
};
