/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetKillmailsKillmailIdKillmailHash200VictimItemsItem } from './getKillmailsKillmailIdKillmailHash200VictimItemsItem';
import type { GetKillmailsKillmailIdKillmailHash200VictimPosition } from './getKillmailsKillmailIdKillmailHash200VictimPosition';

/**
 * victim object
 */
export type GetKillmailsKillmailIdKillmailHash200Victim = {
  /** alliance_id integer */
  alliance_id?: number;
  /** character_id integer */
  character_id?: number;
  /** corporation_id integer */
  corporation_id?: number;
  /** How much total damage was taken by the victim
 */
  damage_taken: number;
  /** faction_id integer */
  faction_id?: number;
  /** items array */
  items?: GetKillmailsKillmailIdKillmailHash200VictimItemsItem[];
  /** Coordinates of the victim in Cartesian space relative to the Sun
 */
  position?: GetKillmailsKillmailIdKillmailHash200VictimPosition;
  /** The ship that the victim was piloting and was destroyed
 */
  ship_type_id: number;
};
