/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetKillmailsKillmailIdKillmailHash200VictimItemsItemItemsItem } from './getKillmailsKillmailIdKillmailHash200VictimItemsItemItemsItem';

/**
 * item object
 */
export type GetKillmailsKillmailIdKillmailHash200VictimItemsItem = {
  /** Flag for the location of the item
 */
  flag: number;
  /** item_type_id integer */
  item_type_id: number;
  /** items array */
  items?: GetKillmailsKillmailIdKillmailHash200VictimItemsItemItemsItem[];
  /** How many of the item were destroyed if any
 */
  quantity_destroyed?: number;
  /** How many of the item were dropped if any
 */
  quantity_dropped?: number;
  /** singleton integer */
  singleton: number;
};
