/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { DatasourceParameter } from './datasourceParameter';
import type { LanguageParameter } from './languageParameter';

export type GetMarketsGroupsMarketGroupIdParams = { datasource?: DatasourceParameter; language?: LanguageParameter };
