/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { DatasourceParameter } from './datasourceParameter';
import type { GetMarketsRegionIdOrdersOrderType } from './getMarketsRegionIdOrdersOrderType';
import type { PageParameter } from './pageParameter';

export type GetMarketsRegionIdOrdersParams = { datasource?: DatasourceParameter; order_type?: GetMarketsRegionIdOrdersOrderType; page?: PageParameter; type_id?: number };
