/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetMarketsPrices200Item = {
  /** adjusted_price number */
  adjusted_price?: number;
  /** average_price number */
  average_price?: number;
  /** type_id integer */
  type_id: number;
};
