/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetOpportunitiesGroupsGroupId200 = {
  /** The groups that are connected to this group on the opportunities map */
  connected_groups: number[];
  /** description string */
  description: string;
  /** group_id integer */
  group_id: number;
  /** name string */
  name: string;
  /** notification string */
  notification: string;
  /** Tasks need to complete for this group */
  required_tasks: number[];
};
