/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetStatus200 = {
  /** Current online player count */
  players: number;
  /** Running version as string */
  server_version: string;
  /** Server start timestamp */
  start_time: string;
  /** If the server is in VIP mode */
  vip?: boolean;
};
