/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetSovereigntyCampaigns200ItemEventType } from './getSovereigntyCampaigns200ItemEventType';
import type { GetSovereigntyCampaigns200ItemParticipantsItem } from './getSovereigntyCampaigns200ItemParticipantsItem';

/**
 * 200 ok object
 */
export type GetSovereigntyCampaigns200Item = {
  /** Score for all attacking parties, only present in Defense Events.
 */
  attackers_score?: number;
  /** Unique ID for this campaign. */
  campaign_id: number;
  /** The constellation in which the campaign will take place.
 */
  constellation_id: number;
  /** Defending alliance, only present in Defense Events
 */
  defender_id?: number;
  /** Score for the defending alliance, only present in Defense Events.
 */
  defender_score?: number;
  /** Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as "Defense Events", station_freeport as "Freeport Events".
 */
  event_type: GetSovereigntyCampaigns200ItemEventType;
  /** Alliance participating and their respective scores, only present in Freeport Events.
 */
  participants?: GetSovereigntyCampaigns200ItemParticipantsItem[];
  /** The solar system the structure is located in.
 */
  solar_system_id: number;
  /** Time the event is scheduled to start.
 */
  start_time: string;
  /** The structure item ID that is related to this campaign.
 */
  structure_id: number;
};
