/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetUniverseRegionsRegionId200 = {
  /** constellations array */
  constellations: number[];
  /** description string */
  description?: string;
  /** name string */
  name: string;
  /** region_id integer */
  region_id: number;
};
