/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 201 created object
 */
export type PostFleetsFleetIdWings201 = {
  /** The wing_id of the newly created wing */
  wing_id: number;
};
