/**
 * Smoke suite for the deployed app.
 *
 * This replaces the stock Cypress example specs, which exercised
 * example.cypress.io and jsonplaceholder.cypress.io rather than JitaSpace — so
 * the CI job built and booted the app, then tested somebody else's site, and a
 * network blip at those hosts failed the build.
 *
 * Deliberately shallow. It answers "did this deploy come up and serve real
 * pages", which is what the cypress workflow actually gates. Assertions lean on
 * `/about`, a client component whose shell renders without the database, so a
 * failure means the app is broken rather than that the seed data is empty.
 */

describe("app boots and serves pages", () => {
  it("serves the homepage without crashing", () => {
    // Not asserting 200: CI runs against a freshly pushed, empty schema, and
    // the point here is to catch a crash, not to pin the empty-data response.
    cy.request({ url: "/", failOnStatusCode: false })
      .its("status")
      .should("be.lessThan", 500);
  });

  it("renders /about inside the shared layout", () => {
    cy.visit("/about");
    cy.title().should("match", /JitaSpace/i);
    cy.contains("h1", "About").should("be.visible");
    // Rendered by MainLayout, which wraps every route — its presence means the
    // root layout rendered rather than an error boundary.
    cy.get('a[href="https://www.eveonline.com/partners"]').should("exist");
  });

  it("serves the PWA manifest generated by app/manifest.ts", () => {
    cy.request("/manifest.webmanifest").then((res) => {
      expect(res.status).to.eq(200);
      expect(`${res.headers["content-type"]}`).to.match(/manifest|json/i);
    });
  });

  it("returns 404 for an unknown route rather than crashing", () => {
    cy.request({ url: "/this-route-does-not-exist", failOnStatusCode: false })
      .its("status")
      .should("eq", 404);
  });
});
