/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetAlliancesAllianceId200 = {
  /** ID of the corporation that created the alliance */
  creator_corporation_id: number;
  /** ID of the character that created the alliance */
  creator_id: number;
  /** date_founded string */
  date_founded: string;
  /** the executor corporation ID, if this alliance is not closed */
  executor_corporation_id?: number;
  /** Faction ID this alliance is fighting for, if this alliance is enlisted in factional warfare */
  faction_id?: number;
  /** the full name of the alliance */
  name: string;
  /** the short name of the alliance */
  ticker: string;
};
