/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdContracts200ItemAvailability } from './getCharactersCharacterIdContracts200ItemAvailability';
import type { GetCharactersCharacterIdContracts200ItemStatus } from './getCharactersCharacterIdContracts200ItemStatus';
import type { GetCharactersCharacterIdContracts200ItemType } from './getCharactersCharacterIdContracts200ItemType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdContracts200Item = {
  /** Who will accept the contract */
  acceptor_id: number;
  /** ID to whom the contract is assigned, can be alliance, corporation or character ID */
  assignee_id: number;
  /** To whom the contract is available */
  availability: GetCharactersCharacterIdContracts200ItemAvailability;
  /** Buyout price (for Auctions only) */
  buyout?: number;
  /** Collateral price (for Couriers only) */
  collateral?: number;
  /** contract_id integer */
  contract_id: number;
  /** Date of confirmation of contract */
  date_accepted?: string;
  /** Date of completed of contract */
  date_completed?: string;
  /** Expiration date of the contract */
  date_expired: string;
  /** Сreation date of the contract */
  date_issued: string;
  /** Number of days to perform the contract */
  days_to_complete?: number;
  /** End location ID (for Couriers contract) */
  end_location_id?: number;
  /** true if the contract was issued on behalf of the issuer's corporation */
  for_corporation: boolean;
  /** Character's corporation ID for the issuer */
  issuer_corporation_id: number;
  /** Character ID for the issuer */
  issuer_id: number;
  /** Price of contract (for ItemsExchange and Auctions) */
  price?: number;
  /** Remuneration for contract (for Couriers only) */
  reward?: number;
  /** Start location ID (for Couriers contract) */
  start_location_id?: number;
  /** Status of the the contract */
  status: GetCharactersCharacterIdContracts200ItemStatus;
  /** Title of the contract */
  title?: string;
  /** Type of the contract */
  type: GetCharactersCharacterIdContracts200ItemType;
  /** Volume of items in the contract */
  volume?: number;
};
