/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdPlanets200ItemPlanetType } from './getCharactersCharacterIdPlanets200ItemPlanetType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdPlanets200Item = {
  /** last_update string */
  last_update: string;
  /** num_pins integer */
  num_pins: number;
  /** owner_id integer */
  owner_id: number;
  /** planet_id integer */
  planet_id: number;
  /** planet_type string */
  planet_type: GetCharactersCharacterIdPlanets200ItemPlanetType;
  /** solar_system_id integer */
  solar_system_id: number;
  /** upgrade_level integer */
  upgrade_level: number;
};
