/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdMail200ItemRecipientsItem } from './getCharactersCharacterIdMail200ItemRecipientsItem';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdMail200Item = {
  /** From whom the mail was sent */
  from?: number;
  /** is_read boolean */
  is_read?: boolean;
  /** labels array */
  labels?: number[];
  /** mail_id integer */
  mail_id?: number;
  /** Recipients of the mail */
  recipients?: GetCharactersCharacterIdMail200ItemRecipientsItem[];
  /** Mail subject */
  subject?: string;
  /** When the mail was sent */
  timestamp?: string;
};
