/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetailsHeadsItem } from './getCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetailsHeadsItem';

/**
 * extractor_details object
 */
export type GetCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetails = {
  /** in seconds */
  cycle_time?: number;
  /** head_radius number */
  head_radius?: number;
  /** heads array */
  heads: GetCharactersCharacterIdPlanetsPlanetId200PinsItemExtractorDetailsHeadsItem[];
  /** product_type_id integer */
  product_type_id?: number;
  /** qty_per_cycle integer */
  qty_per_cycle?: number;
};
