/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdMining200Item = {
  /** date string */
  date: string;
  /** quantity integer */
  quantity: number;
  /** solar_system_id integer */
  solar_system_id: number;
  /** type_id integer */
  type_id: number;
};
