/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * fuel object
 */
export type GetCorporationsCorporationIdStarbasesStarbaseId200FuelsItem = {
  /** quantity integer */
  quantity: number;
  /** type_id integer */
  type_id: number;
};
