/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdBlueprints200ItemLocationFlag } from './getCharactersCharacterIdBlueprints200ItemLocationFlag';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdBlueprints200Item = {
  /** Unique ID for this item. */
  item_id: number;
  /** Type of the location_id */
  location_flag: GetCharactersCharacterIdBlueprints200ItemLocationFlag;
  /** References a station, a ship or an item_id if this blueprint is located within a container. If the return value is an item_id, then the Character AssetList API must be queried to find the container using the given item_id to determine the correct location of the Blueprint. */
  location_id: number;
  /** Material Efficiency Level of the blueprint. */
  material_efficiency: number;
  /** A range of numbers with a minimum of -2 and no maximum value where -1 is an original and -2 is a copy. It can be a positive integer if it is a stack of blueprint originals fresh from the market (e.g. no activities performed on them yet). */
  quantity: number;
  /** Number of runs remaining if the blueprint is a copy, -1 if it is an original. */
  runs: number;
  /** Time Efficiency Level of the blueprint. */
  time_efficiency: number;
  /** type_id integer */
  type_id: number;
};
