/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * action string
 */
export type GetCorporationsCorporationIdContainersLogs200ItemAction = typeof GetCorporationsCorporationIdContainersLogs200ItemAction[keyof typeof GetCorporationsCorporationIdContainersLogs200ItemAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdContainersLogs200ItemAction = {
  add: 'add',
  assemble: 'assemble',
  configure: 'configure',
  enter_password: 'enter_password',
  lock: 'lock',
  move: 'move',
  repackage: 'repackage',
  set_name: 'set_name',
  set_password: 'set_password',
  unlock: 'unlock',
} as const;
