/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * status string
 */
export type GetCharactersCharacterIdMedals200ItemStatus = typeof GetCharactersCharacterIdMedals200ItemStatus[keyof typeof GetCharactersCharacterIdMedals200ItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdMedals200ItemStatus = {
  public: 'public',
  private: 'private',
} as const;
