/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * location_type string
 */
export type GetCharactersCharacterIdClones200HomeLocationLocationType = typeof GetCharactersCharacterIdClones200HomeLocationLocationType[keyof typeof GetCharactersCharacterIdClones200HomeLocationLocationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdClones200HomeLocationLocationType = {
  station: 'station',
  structure: 'structure',
} as const;
