/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * role string
 */
export type GetCharactersCharacterIdRoles200RolesItem = typeof GetCharactersCharacterIdRoles200RolesItem[keyof typeof GetCharactersCharacterIdRoles200RolesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCharactersCharacterIdRoles200RolesItem = {
  Account_Take_1: 'Account_Take_1',
  Account_Take_2: 'Account_Take_2',
  Account_Take_3: 'Account_Take_3',
  Account_Take_4: 'Account_Take_4',
  Account_Take_5: 'Account_Take_5',
  Account_Take_6: 'Account_Take_6',
  Account_Take_7: 'Account_Take_7',
  Accountant: 'Accountant',
  Auditor: 'Auditor',
  Communications_Officer: 'Communications_Officer',
  Config_Equipment: 'Config_Equipment',
  Config_Starbase_Equipment: 'Config_Starbase_Equipment',
  Container_Take_1: 'Container_Take_1',
  Container_Take_2: 'Container_Take_2',
  Container_Take_3: 'Container_Take_3',
  Container_Take_4: 'Container_Take_4',
  Container_Take_5: 'Container_Take_5',
  Container_Take_6: 'Container_Take_6',
  Container_Take_7: 'Container_Take_7',
  Contract_Manager: 'Contract_Manager',
  Diplomat: 'Diplomat',
  Director: 'Director',
  Factory_Manager: 'Factory_Manager',
  Fitting_Manager: 'Fitting_Manager',
  Hangar_Query_1: 'Hangar_Query_1',
  Hangar_Query_2: 'Hangar_Query_2',
  Hangar_Query_3: 'Hangar_Query_3',
  Hangar_Query_4: 'Hangar_Query_4',
  Hangar_Query_5: 'Hangar_Query_5',
  Hangar_Query_6: 'Hangar_Query_6',
  Hangar_Query_7: 'Hangar_Query_7',
  Hangar_Take_1: 'Hangar_Take_1',
  Hangar_Take_2: 'Hangar_Take_2',
  Hangar_Take_3: 'Hangar_Take_3',
  Hangar_Take_4: 'Hangar_Take_4',
  Hangar_Take_5: 'Hangar_Take_5',
  Hangar_Take_6: 'Hangar_Take_6',
  Hangar_Take_7: 'Hangar_Take_7',
  Junior_Accountant: 'Junior_Accountant',
  Personnel_Manager: 'Personnel_Manager',
  Rent_Factory_Facility: 'Rent_Factory_Facility',
  Rent_Office: 'Rent_Office',
  Rent_Research_Facility: 'Rent_Research_Facility',
  Security_Officer: 'Security_Officer',
  Starbase_Defense_Operator: 'Starbase_Defense_Operator',
  Starbase_Fuel_Technician: 'Starbase_Fuel_Technician',
  Station_Manager: 'Station_Manager',
  Trader: 'Trader',
} as const;
