/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdCalendar200ItemEventResponse } from './getCharactersCharacterIdCalendar200ItemEventResponse';

/**
 * event
 */
export type GetCharactersCharacterIdCalendar200Item = {
  /** event_date string */
  event_date?: string;
  /** event_id integer */
  event_id?: number;
  /** event_response string */
  event_response?: GetCharactersCharacterIdCalendar200ItemEventResponse;
  /** importance integer */
  importance?: number;
  /** title string */
  title?: string;
};
