/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdContacts200ItemContactType } from './getCorporationsCorporationIdContacts200ItemContactType';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdContacts200Item = {
  /** contact_id integer */
  contact_id: number;
  /** contact_type string */
  contact_type: GetCorporationsCorporationIdContacts200ItemContactType;
  /** Whether this contact is being watched */
  is_watched?: boolean;
  /** label_ids array */
  label_ids?: number[];
  /** Standing of the contact */
  standing: number;
};
