/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdSearch200 = {
  /** agent array */
  agent?: number[];
  /** alliance array */
  alliance?: number[];
  /** character array */
  character?: number[];
  /** constellation array */
  constellation?: number[];
  /** corporation array */
  corporation?: number[];
  /** faction array */
  faction?: number[];
  /** inventory_type array */
  inventory_type?: number[];
  /** region array */
  region?: number[];
  /** solar_system array */
  solar_system?: number[];
  /** station array */
  station?: number[];
  /** structure array */
  structure?: number[];
};
