/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Type of password set if action is of type SetPassword or EnterPassword
 */
export type GetCorporationsCorporationIdContainersLogs200ItemPasswordType = typeof GetCorporationsCorporationIdContainersLogs200ItemPasswordType[keyof typeof GetCorporationsCorporationIdContainersLogs200ItemPasswordType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCorporationsCorporationIdContainersLogs200ItemPasswordType = {
  config: 'config',
  general: 'general',
} as const;
