/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCorporationsCorporationIdDivisions200HangarItem } from './getCorporationsCorporationIdDivisions200HangarItem';
import type { GetCorporationsCorporationIdDivisions200WalletItem } from './getCorporationsCorporationIdDivisions200WalletItem';

/**
 * 200 ok object
 */
export type GetCorporationsCorporationIdDivisions200 = {
  /** hangar array */
  hangar?: GetCorporationsCorporationIdDivisions200HangarItem[];
  /** wallet array */
  wallet?: GetCorporationsCorporationIdDivisions200WalletItem[];
};
