/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetCharactersCharacterIdContacts200ItemContactType } from './getCharactersCharacterIdContacts200ItemContactType';

/**
 * 200 ok object
 */
export type GetCharactersCharacterIdContacts200Item = {
  /** contact_id integer */
  contact_id: number;
  /** contact_type string */
  contact_type: GetCharactersCharacterIdContacts200ItemContactType;
  /** Whether this contact is in the blocked list. Note a missing value denotes unknown, not true or false */
  is_blocked?: boolean;
  /** Whether this contact is being watched */
  is_watched?: boolean;
  /** label_ids array */
  label_ids?: number[];
  /** Standing of the contact */
  standing: number;
};
