/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetDogmaDynamicItemsTypeIdItemId200DogmaAttributesItem } from './getDogmaDynamicItemsTypeIdItemId200DogmaAttributesItem';
import type { GetDogmaDynamicItemsTypeIdItemId200DogmaEffectsItem } from './getDogmaDynamicItemsTypeIdItemId200DogmaEffectsItem';

/**
 * 200 ok object
 */
export type GetDogmaDynamicItemsTypeIdItemId200 = {
  /** The ID of the character who created the item */
  created_by: number;
  /** dogma_attributes array */
  dogma_attributes: GetDogmaDynamicItemsTypeIdItemId200DogmaAttributesItem[];
  /** dogma_effects array */
  dogma_effects: GetDogmaDynamicItemsTypeIdItemId200DogmaEffectsItem[];
  /** The type ID of the mutator used to generate the dynamic item. */
  mutator_type_id: number;
  /** The type ID of the source item the mutator was applied to create the dynamic item. */
  source_type_id: number;
};
