/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * squad object
 */
export type GetFleetsFleetIdWings200ItemSquadsItem = {
  /** id integer */
  id: number;
  /** name string */
  name: string;
};
