/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwLeaderboardsCorporations200VictoryPointsActiveTotalItem } from './getFwLeaderboardsCorporations200VictoryPointsActiveTotalItem';
import type { GetFwLeaderboardsCorporations200VictoryPointsLastWeekItem } from './getFwLeaderboardsCorporations200VictoryPointsLastWeekItem';
import type { GetFwLeaderboardsCorporations200VictoryPointsYesterdayItem } from './getFwLeaderboardsCorporations200VictoryPointsYesterdayItem';

/**
 * Top 10 rankings of corporations by victory points from yesterday, last week and in total
 */
export type GetFwLeaderboardsCorporations200VictoryPoints = {
  /** Top 10 ranking of corporations active in faction warfare by total victory points. A corporation is considered "active" if they have participated in faction warfare in the past 14 days */
  active_total: GetFwLeaderboardsCorporations200VictoryPointsActiveTotalItem[];
  /** Top 10 ranking of corporations by victory points in the past week */
  last_week: GetFwLeaderboardsCorporations200VictoryPointsLastWeekItem[];
  /** Top 10 ranking of corporations by victory points in the past day */
  yesterday: GetFwLeaderboardsCorporations200VictoryPointsYesterdayItem[];
};
