/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetFwLeaderboardsCorporations200Kills } from './getFwLeaderboardsCorporations200Kills';
import type { GetFwLeaderboardsCorporations200VictoryPoints } from './getFwLeaderboardsCorporations200VictoryPoints';

/**
 * 200 ok object
 */
export type GetFwLeaderboardsCorporations200 = {
  /** Top 10 rankings of corporations by number of kills from yesterday, last week and in total */
  kills: GetFwLeaderboardsCorporations200Kills;
  /** Top 10 rankings of corporations by victory points from yesterday, last week and in total */
  victory_points: GetFwLeaderboardsCorporations200VictoryPoints;
};
