/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Summary of victory points gained for the given faction
 */
export type GetFwStats200ItemVictoryPoints = {
  /** Last week's victory points gained */
  last_week: number;
  /** Total victory points gained since faction warfare began */
  total: number;
  /** Yesterday's victory points gained */
  yesterday: number;
};
