/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetIndustryFacilities200Item = {
  /** ID of the facility */
  facility_id: number;
  /** Owner of the facility */
  owner_id: number;
  /** Region ID where the facility is */
  region_id: number;
  /** Solar system ID where the facility is */
  solar_system_id: number;
  /** Tax imposed by the facility */
  tax?: number;
  /** Type ID of the facility */
  type_id: number;
};
