/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * 200 ok object
 */
export type GetSovereigntyMap200Item = {
  /** alliance_id integer */
  alliance_id?: number;
  /** corporation_id integer */
  corporation_id?: number;
  /** faction_id integer */
  faction_id?: number;
  /** system_id integer */
  system_id: number;
};
