/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetUniverseTypesTypeId200DogmaAttributesItem } from './getUniverseTypesTypeId200DogmaAttributesItem';
import type { GetUniverseTypesTypeId200DogmaEffectsItem } from './getUniverseTypesTypeId200DogmaEffectsItem';

/**
 * 200 ok object
 */
export type GetUniverseTypesTypeId200 = {
  /** capacity number */
  capacity?: number;
  /** description string */
  description: string;
  /** dogma_attributes array */
  dogma_attributes?: GetUniverseTypesTypeId200DogmaAttributesItem[];
  /** dogma_effects array */
  dogma_effects?: GetUniverseTypesTypeId200DogmaEffectsItem[];
  /** graphic_id integer */
  graphic_id?: number;
  /** group_id integer */
  group_id: number;
  /** icon_id integer */
  icon_id?: number;
  /** This only exists for types that can be put on the market */
  market_group_id?: number;
  /** mass number */
  mass?: number;
  /** name string */
  name: string;
  /** packaged_volume number */
  packaged_volume?: number;
  /** portion_size integer */
  portion_size?: number;
  /** published boolean */
  published: boolean;
  /** radius number */
  radius?: number;
  /** type_id integer */
  type_id: number;
  /** volume number */
  volume?: number;
};
