/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { GetWarsWarId200Aggressor } from './getWarsWarId200Aggressor';
import type { GetWarsWarId200AlliesItem } from './getWarsWarId200AlliesItem';
import type { GetWarsWarId200Defender } from './getWarsWarId200Defender';

/**
 * 200 ok object
 */
export type GetWarsWarId200 = {
  /** The aggressor corporation or alliance that declared this war, only contains either corporation_id or alliance_id */
  aggressor: GetWarsWarId200Aggressor;
  /** allied corporations or alliances, each object contains either corporation_id or alliance_id */
  allies?: GetWarsWarId200AlliesItem[];
  /** Time that the war was declared */
  declared: string;
  /** The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id */
  defender: GetWarsWarId200Defender;
  /** Time the war ended and shooting was no longer allowed */
  finished?: string;
  /** ID of the specified war */
  id: number;
  /** Was the war declared mutual by both parties */
  mutual: boolean;
  /** Is the war currently open for allies or not */
  open_for_allies: boolean;
  /** Time the war was retracted but both sides could still shoot each other */
  retracted?: string;
  /** Time when the war started and both sides could shoot each other */
  started?: string;
};
