/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */

/**
 * Fitting location for the item. Entries placed in 'Invalid' will be discarded. If this leaves the fitting with nothing, it will cause an error.
 */
export type PostCharactersCharacterIdFittingsBodyItemsItemFlag = typeof PostCharactersCharacterIdFittingsBodyItemsItemFlag[keyof typeof PostCharactersCharacterIdFittingsBodyItemsItemFlag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCharactersCharacterIdFittingsBodyItemsItemFlag = {
  Cargo: 'Cargo',
  DroneBay: 'DroneBay',
  FighterBay: 'FighterBay',
  HiSlot0: 'HiSlot0',
  HiSlot1: 'HiSlot1',
  HiSlot2: 'HiSlot2',
  HiSlot3: 'HiSlot3',
  HiSlot4: 'HiSlot4',
  HiSlot5: 'HiSlot5',
  HiSlot6: 'HiSlot6',
  HiSlot7: 'HiSlot7',
  Invalid: 'Invalid',
  LoSlot0: 'LoSlot0',
  LoSlot1: 'LoSlot1',
  LoSlot2: 'LoSlot2',
  LoSlot3: 'LoSlot3',
  LoSlot4: 'LoSlot4',
  LoSlot5: 'LoSlot5',
  LoSlot6: 'LoSlot6',
  LoSlot7: 'LoSlot7',
  MedSlot0: 'MedSlot0',
  MedSlot1: 'MedSlot1',
  MedSlot2: 'MedSlot2',
  MedSlot3: 'MedSlot3',
  MedSlot4: 'MedSlot4',
  MedSlot5: 'MedSlot5',
  MedSlot6: 'MedSlot6',
  MedSlot7: 'MedSlot7',
  RigSlot0: 'RigSlot0',
  RigSlot1: 'RigSlot1',
  RigSlot2: 'RigSlot2',
  ServiceSlot0: 'ServiceSlot0',
  ServiceSlot1: 'ServiceSlot1',
  ServiceSlot2: 'ServiceSlot2',
  ServiceSlot3: 'ServiceSlot3',
  ServiceSlot4: 'ServiceSlot4',
  ServiceSlot5: 'ServiceSlot5',
  ServiceSlot6: 'ServiceSlot6',
  ServiceSlot7: 'ServiceSlot7',
  SubSystemSlot0: 'SubSystemSlot0',
  SubSystemSlot1: 'SubSystemSlot1',
  SubSystemSlot2: 'SubSystemSlot2',
  SubSystemSlot3: 'SubSystemSlot3',
} as const;
