/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PostCharactersCharacterIdMailLabelsBodyColor } from './postCharactersCharacterIdMailLabelsBodyColor';

/**
 * label object
 */
export type PostCharactersCharacterIdMailLabelsBody = {
  /** Hexadecimal string representing label color, in RGB format */
  color?: PostCharactersCharacterIdMailLabelsBodyColor;
  /** name string */
  name: string;
};
