/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 * OpenAPI spec version: 1.17
 */
import type { PostCorporationsCorporationIdAssetsLocations200ItemPosition } from './postCorporationsCorporationIdAssetsLocations200ItemPosition';

/**
 * 200 ok object
 */
export type PostCorporationsCorporationIdAssetsLocations200Item = {
  /** item_id integer */
  item_id: number;
  /** position object */
  position: PostCorporationsCorporationIdAssetsLocations200ItemPosition;
};
